name: Fly Deploy
on: [push]

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Create .env file
          run: | 
            touch .env
            echo -e "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
            echo -e "API_SECRET=${{ secrets.API_SECRET }}" >> .env

        - name: Setup fly.io command line tool
          uses: superfly/flyctl-actions/setup-flyctl@master

        - name: "Deploy to fly.io"
          run: flyctl deploy --remote-only --detach
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}